---
- name: Add nginx repository
  apt_repository:
    repo: "deb http://nginx.org/packages/debian/ jessie nginx"

- name: Add nginx repository key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: ensure latest nginx is installed
  apt:
    pkg: nginx
    state: latest
    update_cache: yes

- name: create nginx dirs
  file: name="{{ item }}" state=directory owner=www-data
  with_items:
    - "/etc/nginx/ssl"
    - "/var/log/nginx/{{ ansible_fqdn }}"

- name: copy dh params
  copy:
    src: dhparam.pem
    dest: /etc/nginx/ssl/dhparam.pem
    backup: yes
    owner: www-data
    group: www-data
    mode: 0600
  notify: restart nginx

- name: remove default sites
  file:
    path: "{{ item }}"
    state: absent
  notify: restart nginx
  with_items:
    - /etc/nginx/conf.d/default.conf
    - /etc/nginx/conf.d/example_ssl.conf

- name: add 502 handler that does not leak version info
  copy:
    dest: "/var/www/502.html"
    content: "502: oops, something went wrong"

- name: configure nginx reverse proxy
  template:
    src: reverse_proxy.conf.j2
    dest: /etc/nginx/conf.d/reverse_proxy.conf
  notify: restart nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
